# Site Settings
title: Doctastic!  A free, open-source, and responsive jekyll theme for creating documentation.
email: your-email@domain.com
description: >
  Doctastic is a free, open-source, responsive jekyll theme for creating documentation.

google_analytics_id: UA-77267348-1

# Doctastic Theme Settings
doctastic-logo: /images/Doctastic.png
doctastic-page-type: single

doctastic-primary-color: rgb(96,188,216)
doctastic-primary-color-active: rgb(102,199,229)
doctastic-secondary-color: rgb(245,161,7)
doctastic-secondary-color-active: rgb(250,215,87)

doctastic-main-font: Open Sans
doctastic-accent-font: Open Sans


# Build Settings
collections:
    documentation:
      output: true

markdown: kramdown
kramdown:
  input: GFM

sass:
    style: compressed

gems:
  - jekyll-sitemap