# Site Settings
title: Your Sites Title
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google
  search results) and in your feed.xml site description.


# Doctastic Theme Settings
logo: /images/Doctastic.png
page-type: single # remove this if don't want single


# Build Settings
collections:
    documentation:
      output: true

markdown: kramdown
kramdown:
  input: GFM

sass:
    style: compressed

gems:
  - jekyll-sitemap