# Site Settings
title: Your Sites Title
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google
  search results) and in your feed.xml site description.

google_analytics_id: UA-50755011-1

# Doctastic Theme Settings
doctastic-logo: /assets/images/Doctastic.png
doctastic-logo-section-background-image: /assets/images/top-background-image.jpg
doctastic-page-type: multi

doctastic-primary-color: rgb(96,188,216)
doctastic-primary-color-active: rgb(102,199,229)
doctastic-secondary-color: rgb(245,161,7)
doctastic-secondary-color-active: rgb(250,215,87)

doctastic-main-font: Open Sans
doctastic-accent-font: Open Sans

doctastic-github-repo-url: https://github.com/mattywils/Doctastic

# Build Settings
collections:
    documentation:
      output: true

markdown: kramdown
kramdown:
  input: GFM

sass:
    style: compressed

gems:
  - jekyll-sitemap